import json

# --- Phase 1: The "Plan" (This section would be generated by Bob) ---
# Bob's analysis: "You need a tool to automate code documentation generation."
# Bob's plan: "Create a function that scans for TODO comments and creates a markdown report." Hackathon Guide states: Bob automates complex transformations and streamlines multi-step work.

# --- Phase 2: The "Code" (This is what Bob would help you write) ---
def generate_todo_report(project_files):
    """
    An AI-assisted tool to scan project files for TODO and FIXME comments.
    This automates a mundane but critical task in every project.
    """
    report = {"tasks": [], "summary": {"total": 0}}

    print("🤖 IBM Bob: Analyzing repository context...")

    # Simulate scanning files (Bob would read the actual repo)
    for file_name, content in project_files.items():
        for line_num, line in enumerate(content.split('\n'), 1):
            if 'TODO' in line or 'FIXME' in line:
                report["tasks"].append({
                    "file": file_name,
                    "line": line_num,
                    "text": line.strip()
                })
                report["summary"]["total"] += 1

    # --- Phase 3: The "Output" ---
    # Generate documentation (a core hackathon requirement)
    with open('TODO_REPORT.md', 'w') as f:
        f.write("# Actionable Code Audit\n\n")
        f.write("Generated by IBM Bob Hackathon Submission\n\n")
        for task in report["tasks"]:
            f.write(f"- **{task['file']}** (L:{task['line']}): {task['text']}\n")

    print(f"✅ Report generated: {report['summary']['total']} tasks found.")
    return json.dumps(report, indent=2)

# Example data (In your real project, Bob would pull this from your Git repo)
mock_repo = {
    "app.py": "print('Hello')\n# TODO: Add user authentication\n# FIXME: This is slow",
    "utils.py": "def calculate(): pass\n# TODO: Write unit tests"
}

# Run the agent
if __name__ == "__main__":
    result = generate_todo_report(mock_repo)
    print("\n📊 IBM Bob Export Report Data:\n", result)
